name: "Static Analysis"

on:
  pull_request:
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - psalm*
  push:
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - psalm*

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-22.04"

    strategy:
      fail-fast: false

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.2"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "vendor/bin/phpstan analyse"

  static-analysis-psalm:
    name: "Static Analysis with Psalm"
    runs-on: "ubuntu-22.04"

    strategy:
      fail-fast: false

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.2"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "highest"

      - name: "Run a static analysis with vimeo/psalm"
        run: "vendor/bin/psalm --show-info=false --stats --output-format=github --threads=$(nproc)"
